loaders:
  - modules:
    - haystack_integrations.components.translators.lara.document_translator
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Lara integration for Haystack
  id: integrations-lara
  filename: lara.md
  title: Lara